# Generated by Django 5.0.7 on 2024-08-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dts', '0002_rename_aktif_home_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='price',
            name='level',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
