# Generated by Django 5.0.7 on 2024-08-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dts', '0003_alter_contact_email_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='price',
            name='features',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(),
        ),
    ]
