# Generated by Django 5.0.7 on 2024-08-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dts', '0004_alter_contact_message_alter_price_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
